/* npu_neuralart.c — production implementation of npu_iface.h on LL_ATON
 * (Neural-ART). Replaces npu_stub.c in the target build. Milestone M2.
 *
 * GRAPH: n6_gather2_qdq.onnx, shape d44 (C=88, V=2, T=48, L=12), compiled with
 * the n6-app-safe profile. 13 inputs / 13 outputs: index 0 — x/y, indices
 * 1..12 — state pairs.
 *
 * FOUR THINGS EASY TO GET WRONG THAT GIVE PLAUSIBLE-BUT-WRONG SOUND
 *
 * 1. BUFFER CORRESPONDENCE. The ONNX names (state_in_i) are not in network.h —
 *    only Input_22_out_0 and the like, and the numbering runs downwards. You do
 *    NOT need to know this correspondence: the compiler itself showed that IN_k
 *    and OUT_k are a pair (size, scale and zero-point match, 12 pairs out of
 *    12). The ring closes correctly if you drive OUT_k of hop n into IN_k of
 *    hop n+1 BY INDEX. Here this is also checked by an assert at
 *    initialization instead of being taken on faith.
 *    BUT: the buff_info list in network.c holds more than the graph inputs —
 *    with LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0 ALL weight and bias buffers
 *    (is_param = 1) land there too. They must not be counted together with the
 *    inputs; selection goes strictly by is_param == 0 (caught on the board
 *    3 Aug: prof_err=1).

 * 1a. SHAPE COMES FROM mem_shape, NOT FROM shape. The input has
 *    .shape = {1,2,48,8} but .mem_shape = {1,8,2,48}. The [1, C, V, T] layout
 *    the caller uses is exactly mem_shape (chpos = CHPos_First); shape
 *    describes the tensor in a different axis order and is no good for our
 *    purposes.
 *
 * 2. ZEROING A VOICE IS NOT memset(0). The quantization is asymmetric: zero in
 *    value maps to zero_point, not to a zero byte. memset(...,0,...) would
 *    inject a constant -zp*scale into every state channel; with zp down to -119
 *    and scale up to 0.064 that is a huge value. We write exactly zero_point,
 *    which is its own for each buffer.
 *
 * 3. BALANCING SCALES. The graph is quantized AFTER balance_graph: the input is
 *    divided by n6_npu_s_in[b], the output is multiplied by n6_npu_s_out[b]
 *    (fw/n6_npu_scales.h, generated by train/quantize_gather2.py). Skip it and
 *    you get a band imbalance of 20-30 dB.
 *
 * 4. QUANTIZATION PARAMETERS COME FROM THE GRAPH, not from a constant.
 *    scale/zero_point are read from LL_Buffer_InfoTypeDef, so requantizing the
 *    model does not require a firmware change.
 *
 * MEMORY. Generated with allocate-inputs/allocate-outputs: the buffers belong
 * to the runtime and live inside the activations, so POINTER ping-pong is
 * impossible — n6_npu_swap_states copies 43.7 kB OUT->IN. If that turns out to
 * be expensive, regenerate with user-allocated IO and bring the real swap back.
 *
 * COOPERATIVENESS. LL_ATON_OSAL_WFE() is DELIBERATELY not called here: per
 * §8.1 step 4, between poll() calls the M55 renders the skeleton instead of
 * sleeping.
 */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#include "ll_aton_runtime.h"
#include "ll_aton_caches_interface.h"

#include "npu_iface.h"
#include "n6_config.h"
#include "../n6_npu_scales.h"      /* n6_npu_s_in[4], n6_npu_s_out[4] */

LL_ATON_DECLARE_NAMED_NN_INSTANCE_AND_INTERFACE(network)

#define N6_NPU_STATES  12          /* L=12 state pairs */
#define N6_NPU_NBUF    (1 + N6_NPU_STATES)

/* Profiling of t_call and the number of blocks per hop (metric D-14). Read
 * from main.c/heartbeat. Cleared in submit, latched on DONE. */
uint32_t n6_npu_prof_cycles = 0;
uint32_t n6_npu_prof_epochs = 0;
uint32_t n6_npu_prof_err    = 0;   /* != 0 — shape mismatch, see create() */

#if defined(N6_TARGET) && !defined(N6_NPU_NO_PROF)
#define N6_CYC()  (DWT->CYCCNT)
#else
#define N6_CYC()  (0u)
#endif

uint32_t n6_npu_swap_copy  = 0;   /* cycles in copying */
uint32_t n6_npu_swap_cache = 0;   /* cycles in invalidate/clean */

/* --- wide copy instead of memcpy (4 Aug) --------------------------------
 * Splitting the measurement gave 270 362 cycles for the copying against
 * 34 575 for cache maintenance: it is not the cache, it is the copying
 * itself — 6.2 cycles per byte.
 *
 * memcpy from newlib-nano has nothing to do with it. It is NOT byte-by-byte:
 * with aligned pointers it is an unrolled ldr/str loop over 16 words (I read
 * the disassembly of libc_nano.a), and the state buffers are aligned to 4 —
 * the offsets are visible in network_c_info.json. So the bottleneck is not
 * the instructions but the latency of the processor -> npuRAM path. A 43.7 kB
 * copy is 1366 cache lines, and each one takes a read fill, a write fill
 * (write-allocate) and a subsequent eviction: three transactions per line,
 * 4100 transactions for 270 k cycles, that is about 66 cycles per
 * transaction. A plain ldr/str loop does not overlap them — each next one
 * waits for the previous.
 *
 * The cure is memory-level parallelism: MVE loads 16 bytes per instruction,
 * and four loads in a row BEFORE the first store keep four misses
 * outstanding instead of one. The bytes are the same — this is a copy, not
 * arithmetic, the only way to get it wrong is at the boundaries, which is
 * why there is a self-test over all length remainders at initialization.
 *
 * If even that is not enough, the next step is DMA: then the processor does
 * not touch these buffers at all and cache maintenance goes away together
 * with the copying.
 *
 * THE SAME THING CURES THE MOST EXPENSIVE BLOCK OF THE GRAPH (4 Aug,
 * evening). The epoch profile gave 1 019 501 cycles per hop in twelve
 * `Concat` blocks — 32% of the budget, more than everything else together.
 * Reading ST's code showed that it is not the engines and not DMA, but that
 * same library memcpy:
 *
 *   LL_ATON_LIB_Concat (ll_aton_lib.c) picks the fast DMA path only if the
 *   concatenation axis is the LEFTMOST significant one, that is, all
 *   dimensions to the left of it equal one (`axis_is_leftmost`). We
 *   concatenate along the width with shape [1, V=2, T, C=88] — there is a
 *   two on the left, the check fails, and the work goes to the generic
 *   branch at the bottom of the function. And that branch is just four
 *   memcpy calls per block (two per input, by the number of rows V).
 *
 * The arithmetic matches to the third digit and leaves no room for
 * hypotheses. Twelve blocks move 145 728 bytes per hop (that is exactly the
 * compiler's total `est`, it counts Concat as one element per cycle).
 * 1 019 501 / 145 728 = 6.997 cycles per byte — the same price the swap had
 * (6.19), and it is ONE AND THE SAME for all six block sizes: 7.04, 7.01,
 * 6.95, 6.96, 6.91, 6.87. A constant price per byte with no fixed overhead
 * is the signature of a copy loop, not of DMA setup.
 *
 * Hence the decision: define memcpy OURSELVES. Our strong symbol displaces
 * newlib's at link time, and the wide copy reaches ALL the code — including
 * the code we have no right to edit (ST files inside the STEdgeAI
 * installation: editing there would mean the build does not reproduce for
 * anyone but us). No graph regeneration is needed for this, the weights do
 * not change, the NOR does not have to be reflashed.
 *
 * Expectation: 6.997 -> ~1.4 cycles per byte, that is 1 019 501 -> ~200 k.
 * Checked with a single board run; if it does not come true, then the copy
 * is hitting something else, and that will be visible in the same epoch
 * table.
 *
 * ON PLACEMENT. A global memcpy is a primitive of the whole program, not a
 * detail of the NPU, and it belongs in its own file. It is here because
 * adding a file to the CubeIDE project requires a re-import (see the project contracts file),
 * and the measurement matters more than the layout. Once it is confirmed, we
 * move it in a separate step. */
#if defined(__ARM_FEATURE_MVE) && (__ARM_FEATURE_MVE & 1)
#include <arm_mve.h>
#define N6_HAVE_MVE_COPY 1
#endif

#ifdef N6_HAVE_MVE_COPY
/* There is not a single scalar copy loop here, and that is not only about
 * speed: GCC can recognize a byte-by-byte loop and replace it with a call to
 * memcpy — that is, with this very function. The tail shorter than 16 bytes
 * is covered by a predicate, in one pass, so there is nothing to recognize. */
void *memcpy(void *__restrict dst, const void *__restrict src, size_t n)
{
    uint8_t       *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;

    if ((((uintptr_t)d | (uintptr_t)s) & 3u) == 0u) {
        while (n >= 64u) {                  /* four outstanding misses */
            uint32x4_t a = vldrwq_u32((const uint32_t *)(s +  0));
            uint32x4_t b = vldrwq_u32((const uint32_t *)(s + 16));
            uint32x4_t c = vldrwq_u32((const uint32_t *)(s + 32));
            uint32x4_t e = vldrwq_u32((const uint32_t *)(s + 48));
            vstrwq_u32((uint32_t *)(d +  0), a);
            vstrwq_u32((uint32_t *)(d + 16), b);
            vstrwq_u32((uint32_t *)(d + 32), c);
            vstrwq_u32((uint32_t *)(d + 48), e);
            s += 64; d += 64; n -= 64u;
        }
        while (n >= 16u) {
            vstrwq_u32((uint32_t *)d, vldrwq_u32((const uint32_t *)s));
            s += 16; d += 16; n -= 16u;
        }
    } else {
        while (n >= 16u) {        /* any alignment, 16 bytes per pass */
            vstrbq_u8(d, vldrbq_u8(s));
            s += 16; d += 16; n -= 16u;
        }
    }
    if (n) {
        mve_pred16_t p = vctp8q((uint32_t)n);
        vstrbq_p_u8(d, vldrbq_z_u8(s, p), p);
    }
    return dst;
}
#endif

/* Copy self-test. Cross-checking against memcpy is no longer possible —
 * memcpy is ours now, and the test would compare the function with itself.
 * The reference is our own, byte-by-byte, and its pointers are volatile:
 * without that GCC recognizes the loop and substitutes a call to memcpy,
 * which is exactly what we are testing.
 * Coverage: lengths 0..300 (that is the 64-byte loop, the 16-byte loop and
 * the predicated tail) at eight offsets — even ones land in the aligned
 * branch, odd ones in the unaligned one. The return value is checked too:
 * memcpy must return dst, other code relies on that. Called once at
 * initialization; a failure sets prof_err = 8 and is visible in the banner,
 * not in the sound. */
static void n6_ref_copy(volatile uint8_t *d, const volatile uint8_t *s, size_t n)
{
    for (size_t i = 0; i < n; ++i) d[i] = s[i];
}

static int n6_wide_copy_selftest(void)
{
    static uint8_t a[512], b[512], c[512];
    for (int i = 0; i < 512; ++i) a[i] = (uint8_t)(i * 7u + 13u);
    for (int off = 0; off < 8; ++off)
        for (size_t len = 0; len <= 300u; ++len) {
            memset(b, 0xA5, sizeof b); memset(c, 0xA5, sizeof c);
            n6_ref_copy(b + off, a + off, len);
            if (memcpy(c + off, a + off, len) != c + off) return 0;
            if (memcmp(b, c, sizeof b) != 0) return 0;
        }
    return 1;
}

/* ==== USER IO BUFFERS (4 Aug) ============================================
 * A graph built with --no-inputs-allocation/--no-outputs-allocation does not
 * place its inputs and outputs in the pools — the application sets their
 * addresses through LL_ATON_Set_User_Input_Buffer/Output_Buffer. Its presence
 * is visible from LL_ATON_NETWORK_USER_ALLOCATED_INPUTS in network.h, so the
 * file builds with EITHER of the two graphs: with the old one this branch is
 * simply switched off.
 *
 * WHY. Previously the state ring was copied OUT->IN every hop, 43.7 kB, and
 * that cost 307 k cycles (92 k after the wide copy). The copy was unavoidable
 * precisely because the buffers belonged to the runtime and lived inside the
 * activations.
 *
 * Now they can be GLUED TOGETHER: hand out one and the same pointer as input
 * k and as output k. This is legal, and here is the proof from the generation
 * report rather than from general reasoning: state_out_k is declared as
 * Slice(cat_k), that is, a slice of the CONCATENATION, not a slice of
 * state_in. The graph reads state_in while it builds cat_k, and only then
 * writes state_out from the finished cat_k — the order is guaranteed by the
 * data dependency. So the swap turns into nothing: no copying, no cache
 * maintenance.
 *
 * The setter's requirements (visible in the generated network.c): 32-byte
 * alignment (the MCU cache line) and a size not smaller than declared. We
 * check the return value: failing silently here means getting a NULL pointer
 * in the graph.
 *
 * WHERE THE BUFFERS LIVE IS NOT IRRELEVANT (4 Aug, measured). The first
 * version put them in .ram2, that is, in cpuRAM2. The swap did honestly
 * disappear (92 080 -> 213 cycles), but the NPU stage got 343 k more
 * expensive with the processor's work UNCHANGED: the time of the NPU itself
 * grew. It reads these buffers every epoch, and before that the compiler kept
 * them in npuRAM4 — in its own memory, on the short path. Now they are in
 * npuRAM6 (0x34350000, section .npuram): a bank the graph does not occupy at
 * all, 448 kB free. We need 45.5 kB: x 768 + y 384 + twelve states 44 352.
 *
 * THE FLAG COMES FROM THE GRAPH, NOT FROM THE HEADER (4 Aug, caught by a hard
 * fault). The first version was enabled by
 * LL_ATON_NETWORK_USER_ALLOCATED_INPUTS — a macro from network.h, which this
 * file does NOT include. The condition silently turned out to be false, the
 * binding was not performed, the graph's buffers were left without addresses,
 * and the old swap went off copying through garbage pointers. The mistake is
 * not a typo but the choice of flag: a macro from a header is a fact about
 * the TEXT, not about the graph. The fact about the graph lies in the graph
 * itself — the is_user_allocated field of the buffer structure, which is
 * always there and does not depend on any include. The decision is made from
 * it, at runtime; the file builds with any graph without a single conditional
 * build. */
#define N6_NPU_IO_BYTES (48u * 1024u)
static uint8_t g_npu_io[N6_NPU_IO_BYTES]
    __attribute__((section(".npuram"), aligned(32)));
static size_t  g_npu_io_used;
int n6_npu_user_io = 0;               /* 1 = buffers are ours and glued */

static void *io_alloc(uint32_t n)
{
    size_t off = (g_npu_io_used + 31u) & ~(size_t)31u;
    if (off + n > N6_NPU_IO_BYTES) return NULL;
    g_npu_io_used = off + n;
    return &g_npu_io[off];
}

/* ==== EPOCH PROFILE (4 Aug) ==============================================
 * The NPU stage costs 2.53 M M55 cycles per hop — 79% of the budget, the same
 * in silence and while playing. Until now there was nothing to break that
 * down into 88 epochs with, and the estimate "1.5 M in the 54 Hybrid ones"
 * rested on indirect evidence.
 *
 * It turned out the tool is in the runtime itself and is enabled by a single
 * switch. With LL_ATON_EB_DBG_INFO the compiler puts into every epoch block
 * its number, its type and ITS OWN COST ESTIMATE (estimated_npu_cycles —
 * pure NPU, estimated_tot_cycles — with the memory penalty), and the runtime
 * calls the LL_ATON_RT_SetEpochCallback callback at four points: before and
 * after start_epoch_block, before and after end_epoch_block. The callback is
 * invoked for EVERY block, including a hybrid one, whose start_epoch_block ==
 * NULL (verified against ll_aton_runtime.c: the calls sit outside the NULL
 * check).
 *
 * Hence two different quantities, and they must not be confused:
 *   cpu  = (POST_START-PRE_START) + (POST_END-PRE_END) — M55 cycles INSIDE
 *          the block: programming the engines plus the software part of the
 *          hybrid. This is exactly the price the NPU stage charges the CPU.
 *   wall = POST_END-PRE_START — the full time of the block. It includes
 *          waiting for the NPU, during which the M55 renders the skeleton, so
 *          as a "cost" it is meaningless and is kept only for cross-checking
 *          against the compiler's estimate.
 *
 * Statically (parsing network.c on the host) the compiler promises 1 263 056
 * cycles for the whole inference: 703 376 in 15 EC blobs and 559 680 in 54
 * hybrids. The board shows 2.54 M. This profile is what should explain the
 * 1.28 M difference.
 *
 * It is enabled in ST's ll_aton_config.h (the switch sits there commented out
 * for exactly this purpose). The switch must match between the runtime and
 * the generated network.c — otherwise the structure layout drifts apart; that
 * is why it is in the shared header and not in a -D of a single project. */
#ifdef LL_ATON_EB_DBG_INFO
#define N6_EP_MAX 96
uint32_t n6_npu_ep_cpu[N6_EP_MAX];    /* M55 cycles in the block, sum over hops */
uint32_t n6_npu_ep_wall[N6_EP_MAX];   /* full block time, sum over hops */
uint16_t n6_npu_ep_num[N6_EP_MAX];    /* number of the block's first epoch */
uint16_t n6_npu_ep_last[N6_EP_MAX];
uint16_t n6_npu_ep_flags[N6_EP_MAX];
uint32_t n6_npu_ep_est[N6_EP_MAX];    /* the compiler's estimated_tot_cycles */
uint32_t n6_npu_ep_n;                 /* how many blocks were actually seen */
uint32_t n6_npu_ep_hops;              /* hops since the counters were cleared */
uint32_t n6_npu_cpu_hyb;              /* M55 cycles in the hybrids, sum */
uint32_t n6_npu_cpu_ec;               /* M55 cycles in the EC blobs, sum */

static uint32_t ep_t0, ep_t2, ep_cpu_cur;
static const LL_ATON_RT_EpochBlockItem_t *ep_base;

static void n6_ep_cb(LL_ATON_RT_Callbacktype_t ct,
                     const NN_Instance_TypeDef *inst,
                     const LL_ATON_RT_EpochBlockItem_t *eb)
{
    (void)inst;
    if (eb == NULL) return;
    if (ep_base == NULL) ep_base = LL_ATON_EpochBlockItems_network();
    size_t i = (size_t)(eb - ep_base);
    if (i >= N6_EP_MAX) return;

    switch (ct) {
    case LL_ATON_RT_Callbacktype_PRE_START:
        ep_t0 = N6_CYC();
        break;
    case LL_ATON_RT_Callbacktype_POST_START:
        ep_cpu_cur = N6_CYC() - ep_t0;
        break;
    case LL_ATON_RT_Callbacktype_PRE_END:
        ep_t2 = N6_CYC();
        break;
    case LL_ATON_RT_Callbacktype_POST_END: {
        uint32_t now = N6_CYC();
        uint32_t cpu = ep_cpu_cur + (now - ep_t2);
        n6_npu_ep_cpu[i]  += cpu;
        n6_npu_ep_wall[i] += now - ep_t0;
        n6_npu_ep_num[i]   = (uint16_t)eb->epoch_num;
        n6_npu_ep_last[i]  = (uint16_t)eb->last_epoch_num;
        n6_npu_ep_flags[i] = eb->flags;
        n6_npu_ep_est[i]   = (uint32_t)eb->estimated_tot_cycles;
        if (eb->flags & EpochBlock_Flags_hybrid)    n6_npu_cpu_hyb += cpu;
        else if (eb->flags & EpochBlock_Flags_blob) n6_npu_cpu_ec  += cpu;
        if (i + 1u > n6_npu_ep_n) n6_npu_ep_n = (uint32_t)(i + 1u);
        break; }
    default:
        break;
    }
}

/* Line-by-line dump — by the same trick as CK4: one line per call from the
 * supercycle, so as not to block the render (printing from an ISR is
 * forbidden, §8.3). Returns: the line length, or 0 when the dump is finished.
 * It starts counting after n6_npu_ep_arm(); arming clears the accumulators. */
static int ep_dump_i = -1;

void n6_npu_ep_arm(void)
{
    for (int k = 0; k < N6_EP_MAX; ++k) { n6_npu_ep_cpu[k] = 0; n6_npu_ep_wall[k] = 0; }
    n6_npu_cpu_hyb = n6_npu_cpu_ec = 0;
    n6_npu_ep_hops = 0;
    ep_dump_i = -1;
}

int n6_npu_ep_dump_line(char *dst, int cap)
{
    if (cap < 96) return 0;
    uint32_t hp = n6_npu_ep_hops ? n6_npu_ep_hops : 1u;
    int n;
    if (ep_dump_i < 0) {
        ep_dump_i = 0;
        n = snprintf(dst, (size_t)cap,
            "EP TOTAL hops=%lu blocks=%lu | per hop M55 cycles: HYB=%lu EC=%lu"
            " (est — the compiler's estimate, m55 — the processor inside the"
            " block, wall — including the NPU wait)",
            (unsigned long)n6_npu_ep_hops, (unsigned long)n6_npu_ep_n,
            (unsigned long)(n6_npu_cpu_hyb / hp), (unsigned long)(n6_npu_cpu_ec / hp));
        return (n >= cap) ? cap - 1 : n;
    }
    while (ep_dump_i < (int)n6_npu_ep_n) {
        int i = ep_dump_i++;
        uint32_t cpu = n6_npu_ep_cpu[i] / hp;
        if (cpu == 0u && n6_npu_ep_est[i] == 0u) continue;   /* trailing empty block */
        /* labels in Latin on purpose: %-3s pads by BYTES, and Cyrillic would
         * have wrecked the columns (in UTF-8 a letter is two bytes) */
        const char *t = (n6_npu_ep_flags[i] & EpochBlock_Flags_hybrid) ? "HYB"
                      : (n6_npu_ep_flags[i] & EpochBlock_Flags_blob)   ? "EC "
                                                                       : "---";
        n = snprintf(dst, (size_t)cap,
            "EP %02d ep %3d..%-3d %s est=%-7lu m55=%-7lu wall=%lu",
            i, (int)n6_npu_ep_num[i], (int)n6_npu_ep_last[i], t,
            (unsigned long)n6_npu_ep_est[i], (unsigned long)cpu,
            (unsigned long)(n6_npu_ep_wall[i] / hp));
        return (n >= cap) ? cap - 1 : n;
    }
    return 0;
}
#else
void n6_npu_ep_arm(void) {}
int  n6_npu_ep_dump_line(char *dst, int cap) { (void)dst; (void)cap; return 0; }
#endif /* LL_ATON_EB_DBG_INFO */

struct n6_npu {
    /* Pointers to the SELECTED (is_param == 0) entries, by index:
     * [0] = x/y, [1..12] = state pairs. */
    const LL_Buffer_InfoTypeDef *ib[N6_NPU_NBUF], *ob[N6_NPU_NBUF];
    int      V, T;                 /* from the graph shape, checked vs n6_params_t */
    int8_t  *x;                    /* graph input, [CIN][V][T] int8 */
    const int8_t *y;               /* graph output, [COUT][V][T] int8 */
    float    xs, ys;               /* scale of input/output */
    int      xz, yz;               /* zero_point of input/output */
    uint32_t xlen, ylen;
    uint32_t slen[N6_NPU_STATES];  /* lengths of the state pairs */
    int      szp[N6_NPU_STATES];   /* zero_point of each pair */
    uint32_t sC[N6_NPU_STATES];    /* C and W from shape [1,C,V,W] — for zero_voice */
    uint32_t sW[N6_NPU_STATES];
    float   *res;                  /* [COUT][V][T] float, dequantized */
    uint32_t t0;
    int      running, done;
};

/* ----------------------------------------------------------- utilities */
/* Selects the graph entries (is_param == 0) into dst, at most max. Returns
 * the FULL number found — so that a mismatch is visible, not truncated. */
static int collect(const LL_Buffer_InfoTypeDef *b,
                   const LL_Buffer_InfoTypeDef **dst, int max) {
    int n = 0;
    for (int i = 0; b && b[i].name; i++) {
        if (b[i].is_param) continue;          /* weights and biases are not inputs */
        if (n < max) dst[n] = &b[i];
        n++;
    }
    return n;
}

static inline int8_t q8(float v, float inv_scale, int zp) {
    int q = (int)lrintf(v * inv_scale) + zp;
    if (q < -128) q = -128;
    if (q >  127) q =  127;
    return (int8_t)q;
}

/* ------------------------------------------------------------- creation */
n6_npu_t *n6_npu_create(const n6_params_t *prm) {
    static int rt_up = 0;
    n6_npu_t *n = calloc(1, sizeof *n);
    if (!n) return NULL;

    if (!rt_up) { LL_ATON_RT_RuntimeInit(); rt_up = 1; }
    if (!n6_wide_copy_selftest()) { n6_npu_prof_err = 8; return n; }
    LL_ATON_RT_Init_Network(&NN_Instance_network);
#ifdef LL_ATON_EB_DBG_INFO
    LL_ATON_RT_SetEpochCallback(n6_ep_cb, &NN_Instance_network);
    n6_npu_ep_arm();
#endif

    int ni = collect(LL_ATON_Input_Buffers_Info(&NN_Instance_network),
                     n->ib, N6_NPU_NBUF);
    int no = collect(LL_ATON_Output_Buffers_Info(&NN_Instance_network),
                     n->ob, N6_NPU_NBUF);

    /* --- shape contract: we check, we do not assume --- */
    if (ni != N6_NPU_NBUF || no != N6_NPU_NBUF) {
        /* We encode the FACT, not "something is wrong": 1000 + input*100 +
         * output, clipped by a hundred so it fits in one heartbeat number. */
        n6_npu_prof_err = 1000u + (unsigned)(ni % 100) * 100u + (unsigned)(no % 100);
        return n;
    }
    /* x is declared as [1, CIN, V, T] — EXACTLY mem_shape (see item 1a above) */
    if (n->ib[0]->mem_ndims < 4 || !n->ib[0]->mem_shape) { n6_npu_prof_err = 2; return n; }
    n->V = (int)n->ib[0]->mem_shape[2];
    n->T = (int)n->ib[0]->mem_shape[3];
    if ((int)n->ib[0]->mem_shape[1] != N6_NPU_CIN ||
        (int)n->ob[0]->mem_shape[1] != N6_NPU_COUT) { n6_npu_prof_err = 3; return n; }
    if (n->V != prm->n_voices || n->T != prm->hop48 / 4) {
        n6_npu_prof_err = 4; return n;          /* graph and runtime diverged */
    }

    /* Binding happens before the first use of the addresses: until the setter
     * is called, the buffer has no address at all. The setter's indexing
     * matches the graph order, the same one collect() gives: num 0 is x.
     * The condition is a fact from the graph. Checking one buffer is enough:
     * the compiler does not make mixed graphs, but just in case every one of
     * them is cross-checked below. */
    if (n->ib[0]->is_user_allocated) {
        void *b0 = io_alloc(LL_Buffer_len(n->ib[0]));
        void *b1 = io_alloc(LL_Buffer_len(n->ob[0]));
        if (!b0 || !b1) { n6_npu_prof_err = 70; return n; }
        if (LL_ATON_Set_User_Input_Buffer(&NN_Instance_network, 0, b0,
                                          LL_Buffer_len(n->ib[0]))
            != LL_ATON_User_IO_NOERROR) { n6_npu_prof_err = 71; return n; }
        if (LL_ATON_Set_User_Output_Buffer(&NN_Instance_network, 0, b1,
                                           LL_Buffer_len(n->ob[0]))
            != LL_ATON_User_IO_NOERROR) { n6_npu_prof_err = 72; return n; }
        for (int k = 1; k <= N6_NPU_STATES; k++) {
            uint32_t li = LL_Buffer_len(n->ib[k]), lo = LL_Buffer_len(n->ob[k]);
            if (li != lo) { n6_npu_prof_err = 73; return n; }
            void *b = io_alloc(li);
            if (!b) { n6_npu_prof_err = 74; return n; }
            /* ONE buffer per pair — this is where swap_states disappears */
            if (LL_ATON_Set_User_Input_Buffer(&NN_Instance_network, (uint32_t)k, b, li)
                != LL_ATON_User_IO_NOERROR) { n6_npu_prof_err = 75; return n; }
            if (LL_ATON_Set_User_Output_Buffer(&NN_Instance_network, (uint32_t)k, b, lo)
                != LL_ATON_User_IO_NOERROR) { n6_npu_prof_err = 76; return n; }
            if (!n->ib[k]->is_user_allocated || !n->ob[k]->is_user_allocated) {
                n6_npu_prof_err = 77; return n;   /* graph is internally inconsistent */
            }
        }
        n6_npu_user_io = 1;
    }

    n->x    = (int8_t *)LL_Buffer_addr_start(n->ib[0]);
    n->y    = (const int8_t *)LL_Buffer_addr_start(n->ob[0]);
    n->xlen = LL_Buffer_len(n->ib[0]);
    n->ylen = LL_Buffer_len(n->ob[0]);
    if (n->xlen != (uint32_t)(N6_NPU_CIN  * n->V * n->T) ||
        n->ylen != (uint32_t)(N6_NPU_COUT * n->V * n->T)) {
        n6_npu_prof_err = 5; return n;
    }
    if (n->ib[0]->per_channel || !n->ib[0]->scale || !n->ib[0]->offset ||
        n->ob[0]->per_channel || !n->ob[0]->scale || !n->ob[0]->offset) {
        n6_npu_prof_err = 6; return n;          /* we expect per-tensor io */
    }
    n->xs = n->ib[0]->scale[0];  n->xz = (int)n->ib[0]->offset[0];
    n->ys = n->ob[0]->scale[0];  n->yz = (int)n->ob[0]->offset[0];

    /* --- state pairs: lengths and quantization must match index by index.
     * Matching scale/zp is a direct consequence of tie_state_scales; if that
     * is broken, requantization goes round the ring, and catching it by ear
     * is too late. --- */
    for (int k = 0; k < N6_NPU_STATES; k++) {
        const LL_Buffer_InfoTypeDef *i = n->ib[k + 1], *o = n->ob[k + 1];
        if (LL_Buffer_len(i) != LL_Buffer_len(o)) { n6_npu_prof_err = 10 + k; return n; }
        if (!i->scale || !o->scale || !i->offset || !o->offset ||
            i->scale[0] != o->scale[0] || i->offset[0] != o->offset[0]) {
            n6_npu_prof_err = 30 + k; return n;
        }
        if (i->mem_ndims < 4 || !i->mem_shape || (int)i->mem_shape[2] != n->V) {
            n6_npu_prof_err = 50 + k; return n;
        }
        n->slen[k] = LL_Buffer_len(i);
        n->szp[k]  = (int)i->offset[0];
        n->sC[k]   = i->mem_shape[1];
        n->sW[k]   = i->mem_shape[3];
    }

    n->res = calloc((size_t)N6_NPU_COUT * n->V * n->T, sizeof(float));
    if (!n->res) { n6_npu_prof_err = 7; return n; }

    /* States at start = "silence", that is zero_point, not a zero byte. */
    for (int k = 0; k < N6_NPU_STATES; k++) {
        memset(LL_Buffer_addr_start(n->ib[k + 1]),
               (uint8_t)(int8_t)n->szp[k], n->slen[k]);
        LL_ATON_Cache_MCU_Clean_Range(
            (uintptr_t)LL_Buffer_addr_start(n->ib[k + 1]), n->slen[k]);
    }
    n->done = 1;                    /* before the first submit residual = zeros */
    return n;
}

/* --------------------------------------------------------------- submit */
void n6_npu_submit(n6_npu_t *n, const float *xc /*[CIN][V][T]*/) {
    if (!n || n6_npu_prof_err) return;
    const int VT = n->V * n->T;
    const float inv = 1.0f / n->xs;

    /* Bands 0..3 are divided by the balancing scale; channels 4..7
     * (amp/tA/tB/t) were not balanced — we pass them through as they are. */
    for (int c = 0; c < N6_NPU_CIN; c++) {
        const float g = (c < N6_BANDS) ? (inv / n6_npu_s_in[c]) : inv;
        const float *src = xc + (size_t)c * VT;
        int8_t      *dst = n->x + (size_t)c * VT;
        for (int i = 0; i < VT; i++) dst[i] = q8(src[i], g, n->xz);
    }
    LL_ATON_Cache_MCU_Clean_Range((uintptr_t)n->x, n->xlen);

    LL_ATON_RT_Reset_Network(&NN_Instance_network);
    n->running = 1;
    n->done    = 0;
    n6_npu_prof_epochs = 0;
    n->t0 = N6_CYC();
}

/* ----------------------------------------------------------------- poll */
int n6_npu_poll(n6_npu_t *n) {
    if (!n || n6_npu_prof_err) return 1;
    if (n->done) return 1;

    /* One epoch block per call. We deliberately do not call WFE: between
     * polls the M55 renders the skeleton — that is the whole point of
     * cooperative pumping (§8.1). */
    LL_ATON_RT_RetValues_t r = LL_ATON_RT_RunEpochBlock(&NN_Instance_network);
    n6_npu_prof_epochs++;
    if (r != LL_ATON_RT_DONE) return 0;

    n6_npu_prof_cycles = N6_CYC() - n->t0;
#ifdef LL_ATON_EB_DBG_INFO
    n6_npu_ep_hops++;
#endif
    LL_ATON_Cache_MCU_Invalidate_Range((uintptr_t)n->y, n->ylen);

    const int VT = n->V * n->T;
    for (int b = 0; b < N6_NPU_COUT; b++) {
        const float g = n->ys * n6_npu_s_out[b];
        const int8_t *src = n->y + (size_t)b * VT;
        float        *dst = n->res + (size_t)b * VT;
        for (int i = 0; i < VT; i++) dst[i] = (float)((int)src[i] - n->yz) * g;
    }
    n->running = 0;
    n->done    = 1;
    return 1;
}

const float *n6_npu_residual(const n6_npu_t *n) { return n->res; }

/* ------------------------------------------------------------ zero_voice
 * §8.2/R-3: call it ONLY after DONE and ONLY on the output set — otherwise
 * there is a race with the write of state_out. State layout [1, C, V, W]: the
 * slice of voice v lies in contiguous chunks of W bytes with a stride of V*W. */
void n6_npu_zero_voice(n6_npu_t *n, int v) {
    if (!n || n6_npu_prof_err || !n->done) return;
    if (v < 0 || v >= n->V) return;
    for (int k = 0; k < N6_NPU_STATES; k++) {
        uint8_t *base = (uint8_t *)LL_Buffer_addr_start(n->ob[k + 1]);
        const uint32_t C = n->sC[k], W = n->sW[k];
        const uint8_t  z = (uint8_t)(int8_t)n->szp[k];   /* NOT 0 — see the header */
        for (uint32_t c = 0; c < C; c++)
            memset(base + ((size_t)c * n->V + v) * W, z, W);
    }
}

/* ----------------------------------------------------------- swap_states
 * There is no real pointer swap: the IO is allocated by the runtime inside
 * the activations. We copy the output ring into the input one — 43.7 kB.
 *
 * MEASUREMENT 4 Aug: 307 460 cycles per hop, that is 9.6% of the budget and
 * 97% of the whole hop "tail". That is SEVEN CYCLES PER BYTE — exactly the
 * same figure as the software Concats inside the graph. The coincidence is
 * suspicious: the one thing both operations have in common is that the
 * processor goes to npuRAM. So the question is not whether memcpy is bad, but
 * which is more expensive — the bandwidth itself or the cache maintenance
 * (12 ranges, 43.7 kB, at 32 bytes per line that is ~1400 invalidate
 * operations plus as many cleans).
 *
 * We split them and measure separately, because the cures for these two cases
 * are different: bandwidth is cured by DMA (the processor stops touching
 * these buffers altogether, and cache maintenance goes away with it), while
 * expensive maintenance is cured by merging the ranges or by a whole-cache
 * operation. */

void n6_npu_swap_states(n6_npu_t *n) {
    if (!n || n6_npu_prof_err) return;
    /* Glued buffers: the output ALREADY lies where the graph expects the input. */
    if (n6_npu_user_io) return;
    for (int k = 0; k < N6_NPU_STATES; k++) {
        void       *in  = LL_Buffer_addr_start(n->ib[k + 1]);
        const void *out = LL_Buffer_addr_start(n->ob[k + 1]);
        uint32_t t0 = N6_CYC();
        LL_ATON_Cache_MCU_Invalidate_Range((uintptr_t)out, n->slen[k]);
        uint32_t t1 = N6_CYC();
        memcpy(in, out, n->slen[k]);
        uint32_t t2 = N6_CYC();
        LL_ATON_Cache_MCU_Clean_Range((uintptr_t)in, n->slen[k]);
        uint32_t t3 = N6_CYC();
        n6_npu_swap_cache += (t1 - t0) + (t3 - t2);
        n6_npu_swap_copy  += (t2 - t1);
    }
}
