/* n6_npu_scales.h — GENERATED by train/quantize_gather2.py.
 * Band balancing around the int8 boundary (see balance_graph).
 *   before submit: x_cond[b][v][t] /= n6_npu_s_in[b]
 *   after DONE:    residual[b][v][t] *= n6_npu_s_out[b]
 * Source: n6_gather2_qdq_eq.onnx
 */
#ifndef N6_NPU_SCALES_H
#define N6_NPU_SCALES_H

static const float n6_npu_s_in[4]  = { 1.0f, 0.0431662621f, 0.0353641307f, 0.0344887303f };
static const float n6_npu_s_out[4] = { 1.0f, 0.112080371f, 0.0795320653f, 0.0737482625f };

#endif
