/* host_test.c — unit tests of the DSP building blocks against the §2.4 golden
 * vectors (fw/test/vectors/*.bin — float32, generated by
 * tools/export_fw_assets.py).
 * Tolerances: the golden is f32, C works in double inside — cross-checked by
 * relative RMS. */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../src/n6_dsp.h"
#include "../src/midi.h"
#include "../src/voice.h"
#include "../src/pipeline.h"
#include "../src/npu_test.h"
#include "../src/n6_fir.h"

#define NFR 600
#define N12 (NFR * N6_HOP12)
#define N48 (NFR * N6_HOP48)

static float *load(const char *name, size_t want)
{
    char path[256];
    snprintf(path, sizeof path, "test/vectors/%s.bin", name);
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "missing %s\n", path); exit(2); }
    float *a = malloc(want * sizeof(float));
    if (fread(a, sizeof(float), want, f) != want) {
        fprintf(stderr, "size %s != %zu\n", path, want); exit(2);
    }
    fclose(f);
    return a;
}

static double rel_rms(const float *a, const float *b, size_t n)
{
    double e = 0, r = 0;
    for (size_t i = 0; i < n; ++i) {
        double d = (double)a[i] - (double)b[i];
        e += d * d; r += (double)b[i] * (double)b[i];
    }
    return sqrt(e / (r + 1e-30));
}

static int test_pqmf(void)
{
    float *sub = load("pqmf_sub", (size_t)4 * N12);
    float *yg  = load("pqmf_y", N48);
    float *y   = malloc(N48 * sizeof(float));
    n6_pqmf_synth_t s; n6_pqmf_synth_init(&s);
    float hop[N6_BANDS][N6_HOP12];
    for (int k = 0; k < NFR; ++k) {
        for (int b = 0; b < 4; ++b)
            memcpy(hop[b], sub + (size_t)b * N12 + (size_t)k * N6_HOP12,
                   N6_HOP12 * sizeof(float));
        n6_pqmf_synth_hop(&s, (const float (*)[N6_HOP12])hop,
                          y + (size_t)k * N6_HOP48, N6_HOP12);
    }
    double e = rel_rms(y, yg, N48);
    printf("[pqmf_synth]  rel RMS = %.3e  %s\n", e, e < 1e-4 ? "OK" : "FAIL");
    free(sub); free(yg); free(y);
    return e < 1e-4;
}

static int test_skeleton_b(void)
{
    float *f0 = load("skb_f0", NFR), *am = load("skb_amp", NFR);
    float *tA = load("skb_tA", NFR), *tB = load("skb_tB", NFR);
    float *gt = load("skb_gate", NFR);
    float *sg = load("skb_sub", (size_t)4 * N12);
    static float sub[N6_BANDS][N12];
    memset(sub, 0, sizeof sub);
    n6_skb_voice_t v; n6_skb_init(&v, 0xC0FFEEu);
    float hop[N6_BANDS][N6_HOP12];
    for (int k = 0; k < NFR; ++k) {
        int k1 = k + 1 < NFR ? k + 1 : k;          /* C-1: the last frame is held */
        n6_frame_t a = { f0[k], am[k], tA[k], tB[k], gt[k] };
        n6_frame_t b = { f0[k1], am[k1], tA[k1], tB[k1], gt[k1] };
        memset(hop, 0, sizeof hop);
        n6_skb_render_hop(&v, &a, &b, hop);
        for (int bb = 0; bb < 4; ++bb)
            memcpy(&sub[bb][k * N6_HOP12], hop[bb], N6_HOP12 * sizeof(float));
    }
    double e = rel_rms(&sub[0][0], sg, (size_t)4 * N12);
    printf("[skeleton_b]  rel RMS = %.3e  %s\n", e, e < 5e-3 ? "OK" : "FAIL");
    free(f0); free(am); free(tA); free(tB); free(gt); free(sg);
    return e < 5e-3;
}

static int test_wowflutter(void)
{
    float *x = load("wf_x", N48), *yg = load("wf_y", N48);
    float *vm = load("wf_v_macro", NFR), *dp = load("wf_depth", NFR);
    float *hl = load("wf_hiss", NFR);
    n6_wf_t w; n6_wf_init(&w, 0xF1A77E12u, 0x8155CAFEu, N48);
    for (int k = 0; k < NFR; ++k) {
        int k1 = k + 1 < NFR ? k + 1 : k;
        n6_wf_hop(&w, x + (size_t)k * N6_HOP48, N6_HOP48,
                  vm[k], vm[k1], dp[k], dp[k1], hl[k], hl[k1]);
    }
    double e = rel_rms(x, yg, N48);
    printf("[wowflutter]  rel RMS = %.3e  %s\n", e, e < 1e-3 ? "OK" : "FAIL");
    free(x); free(yg); free(vm); free(dp); free(hl);
    return e < 1e-3;
}

static int test_midi(void)
{
    n6_midi_parser_t p; n6_midi_parser_init(&p);
    n6_midi_ev_t ev; int n_on = 0, n_off = 0, n_cc = 0;
    const uint8_t stream[] = {
        0x90, 60, 100,            /* NoteOn */
        62, 0xFE, 90,             /* running status + Active Sensing inside! */
        0xF8, 64, 0,              /* realtime + NoteOn vel0 == NoteOff */
        0xB0, 1, 55,              /* CC1 */
        0xF0, 1, 2, 3, 0xF7,      /* SysEx — to be skipped */
        0x80, 60, 0 };
    for (size_t i = 0; i < sizeof stream; ++i)
        if (n6_midi_parse_byte(&p, stream[i], &ev)) {
            if (ev.type == N6_EV_NOTE_ON) n_on++;
            if (ev.type == N6_EV_NOTE_OFF) n_off++;
            if (ev.type == N6_EV_CC) n_cc++;
        }
    int ok = (n_on == 2 && n_off == 2 && n_cc == 1);
    printf("[midi]        on=%d off=%d cc=%d  %s\n", n_on, n_off, n_cc,
           ok ? "OK" : "FAIL");
    return ok;
}

static int test_voice_pipe(void)
{
    n6_params_t prm = N6_PARAMS_DEFAULT;
    n6_pipe_t *p = malloc(sizeof *p);
    n6_pipe_init(p, &prm);
    n6_midi_ev_t ev = { N6_EV_NOTE_ON, 0, 57, 100 };
    n6_vm_event(&p->vm, &ev);
    static float out[N6_HOP48];
    double peak = 0; int nan = 0;
    for (int h = 0; h < 250; ++h) {                /* 1 s integration smoke */
        if (h == 100) { ev.d1 = 69; n6_vm_event(&p->vm, &ev); }  /* 2nd voice */
        if (h == 150) { n6_midi_ev_t off = { N6_EV_NOTE_OFF, 0, 57, 0 };
                        n6_vm_event(&p->vm, &off); }
        n6_pipe_hop(p, out);
        for (int i = 0; i < N6_HOP48; ++i) {
            if (isnan(out[i])) nan = 1;
            if (fabs(out[i]) > peak) peak = fabs(out[i]);
        }
    }
    /* H5 limiter: the peak must stay below the 0.98 threshold (+epsilon) */
    int ok = !nan && peak > 0.01 && peak <= 0.981 && p->npu_miss == 0;
    printf("[pipeline]    1s smoke: peak=%.3f nan=%d npu_miss=%u  %s\n",
           peak, nan, p->npu_miss, ok ? "OK" : "FAIL");
    free(p);
    return ok;
}

/* --------------------------------------------------------------------------
 * Tests of the contract with the NPU. Before 2 Aug there were none, and the
 * zero stub masked three P0s: the voices were summed before the NPU, poll was
 * called once, the input was overwritten before DONE. Both tests fail on the
 * old pipeline.
 * ------------------------------------------------------------------------ */

/* A three-note chord so the voices are DIFFERENT (at V=1 both checks go blind). */
static void play_chord_vel(n6_pipe_t *p, uint8_t vel)
{
    static const uint8_t notes[3] = { 45, 57, 69 };
    for (int i = 0; i < 3; ++i) {
        n6_midi_ev_t ev = { N6_EV_NOTE_ON, 0, notes[i], vel };
        n6_vm_event(&p->vm, &ev);
    }
}
static void play_chord(n6_pipe_t *p) { play_chord_vel(p, 100); }

/* 1) Input layout: the NPU must be handed [CIN][V][T] with a SEPARATE slice
 *    per voice — and must be polled in a loop until DONE. */
static int test_npu_layout(void)
{
    n6_params_t prm = N6_PARAMS_DEFAULT;
    prm.n_voices = 3;
    n6_pipe_t *p = malloc(sizeof *p);
    n6_pipe_init(p, &prm);
    n6_npu_test_latency(p->npu, 3);          /* DONE only from the 3rd poll */
    n6_npu_test_pattern(p->npu, N6_NPUT_VGAIN);
    p->t_macro = 0.37f;
    play_chord(p);

    static float out[N6_HOP48];
    for (int h = 0; h < 40; ++h) n6_pipe_hop(p, out);

    const int V = prm.n_voices, T = N6_HOP12;
    const float *xin = n6_npu_test_last_input(p->npu);
    const int idx = p->cur ^ 1;              /* block handed over in this hop */
    int bad = 0, nz = 0, distinct = 0;
    for (int b = 0; b < N6_BANDS; ++b)
        for (int v = 0; v < V; ++v)
            for (int t = 0; t < T; ++t) {
                float got = xin[((size_t)b * V + v) * T + t];
                float want = p->sub[idx][v][b][t];
                if (got != want) bad++;
                if (want != 0.0f) nz++;
            }
    /* the voice slices must DIFFER: had the voices been summed before the
       NPU, all three slices would coincide (and the zero test below would
       fail too) */
    for (int t = 0; t < T; ++t)
        if (xin[(0 * V + 0) * T + t] != xin[(0 * V + 1) * T + t]) distinct = 1;
    /* conditioning channels */
    int cbad = 0;
    for (int v = 0; v < V; ++v) {
        const n6_frame_t *f = &p->fr_used[idx][v];
        for (int t = 0; t < T; ++t) {
            if (xin[((size_t)4 * V + v) * T + t] != f->amp * f->gate) cbad++;
            if (xin[((size_t)5 * V + v) * T + t] != f->tA)            cbad++;
            if (xin[((size_t)6 * V + v) * T + t] != f->tB)            cbad++;
            if (xin[((size_t)7 * V + v) * T + t] != p->t_macro)       cbad++;
        }
    }
    int ok = !bad && !cbad && nz > 0 && distinct &&
             p->npu_polls == 3 && p->npu_miss == 0;
    printf("[npu layout]  slice!=%d controls!=%d nonzero=%d distinct=%d "
           "polls=%u miss=%u  %s\n", bad, cbad, nz, distinct,
           p->npu_polls, p->npu_miss, ok ? "OK" : "FAIL");
    free(p);
    return ok;
}

/* 2) "Null teacher": residual = -input. With the correct layout and mixer the
 *    skeleton of each voice is cancelled by ITS OWN residual — the chain must
 *    go exactly silent. Summing the voices before the NPU, or indexing the
 *    residual without V, leaves (V-1) uncancelled voices. Hiss and wow off. */
static int test_npu_null_teacher(void)
{
    n6_params_t prm = N6_PARAMS_DEFAULT;
    prm.n_voices = 3;
    n6_pipe_t *p = malloc(sizeof *p);
    n6_pipe_init(p, &prm);
    p->hisslvl = 0.0f; p->wdepth = 0.0f;     /* else noise masks the silence */
    /* The test isolates the NPU CONTRACT. With a production n6_fir_coeffs.h
     * the FIR stage switches itself on, and FIR(skeleton) would be left at
     * the output — the test would fail for no good reason (caught 4 Aug with
     * the first production coefficients). */
    n6_pipe_set_fir(p, NULL);
    n6_npu_test_pattern(p->npu, N6_NPUT_NEGX);
    n6_npu_test_latency(p->npu, 2);
    play_chord(p);

    static float out[N6_HOP48];
    double peak = 0.0, peak_dry = 0.0;
    for (int h = 0; h < 250; ++h) {
        n6_pipe_hop(p, out);
        for (int i = 0; i < N6_HOP48; ++i)
            if (fabs(out[i]) > peak) peak = fabs(out[i]);
    }
    /* sanity control: the same chord WITHOUT cancellation must sound */
    n6_pipe_t *q = malloc(sizeof *q);
    n6_pipe_init(q, &prm);
    q->hisslvl = 0.0f; q->wdepth = 0.0f;
    n6_pipe_set_fir(q, NULL);
    play_chord(q);
    for (int h = 0; h < 250; ++h) {
        n6_pipe_hop(q, out);
        for (int i = 0; i < N6_HOP48; ++i)
            if (fabs(out[i]) > peak_dry) peak_dry = fabs(out[i]);
    }
    int ok = (peak < 1e-9) && (peak_dry > 0.01) && p->npu_miss == 0;
    printf("[npu null]    peak with cancel=%.3e (without cancel %.3f) miss=%u  %s\n",
           peak, peak_dry, p->npu_miss, ok ? "OK" : "FAIL");
    free(p); free(q);
    return ok;
}

/* 3) Sustain: a NoteOff with the pedal down holds the note, releasing the
 *    pedal drops it. Before 2 Aug held notes were never dropped (there is no
 *    second NoteOff). */
static int test_sustain(void)
{
    n6_params_t prm = N6_PARAMS_DEFAULT;
    n6_voicemgr_t m;
    n6_vm_init(&m, &prm);
    n6_frame_t fr[N6_MAX_VOICES];
    n6_midi_ev_t on   = { N6_EV_NOTE_ON,  0, 60, 100 };
    n6_midi_ev_t ped1 = { N6_EV_CC, 0, 64, 127 };
    n6_midi_ev_t off  = { N6_EV_NOTE_OFF, 0, 60, 0 };
    n6_midi_ev_t ped0 = { N6_EV_CC, 0, 64, 0 };
    n6_vm_event(&m, &on);
    n6_vm_event(&m, &ped1);
    n6_vm_event(&m, &off);
    for (int k = 0; k < 250; ++k) n6_vm_tick(&m, fr);     /* 1 s under pedal */
    int held_ok = (m.v[0].st == V_ON) && (fr[0].gate > 0.5f);
    n6_vm_event(&m, &ped0);
    for (int k = 0; k < 250; ++k) n6_vm_tick(&m, fr);     /* 1 s after */
    int rel_ok = (m.v[0].st == V_FREE) || (fr[0].gate < 0.05f);
    /* CC123 panic, just in case */
    n6_vm_event(&m, &on);
    n6_midi_ev_t panic = { N6_EV_CC, 0, 123, 0 };
    n6_vm_event(&m, &panic);
    int panic_ok = (m.v[0].st != V_ON);
    int ok = held_ok && rel_ok && panic_ok;
    printf("[sustain]     holds=%d releases=%d panic=%d  %s\n",
           held_ok, rel_ok, panic_ok, ok ? "OK" : "FAIL");
    return ok;
}

/* 4) The linear zeroth layer (n6_fir): a causal 4->4 FIR bank modulated by
 *    the t axis. The golden was computed by numpy in double precision with a
 *    direct convolution; streaming by hops must match it across block
 *    boundaries. */
static int test_fir(void)
{
    enum { K = N6_FIR_TAPS, NH = 40, NT = NH * N6_HOP12 };
    float *w0 = load("fir_w0", (size_t)N6_BANDS * N6_BANDS * K);
    float *w1 = load("fir_w1", (size_t)N6_BANDS * N6_BANDS * K);
    float *x  = load("fir_x",  (size_t)N6_BANDS * NT);
    float *tv = load("fir_t",  NH);
    float *yg = load("fir_y",  (size_t)N6_BANDS * NT);
    static float y[N6_BANDS][NT];
    n6_fir_coeffs_t c = { w0, w1 };
    n6_fir_t f; n6_fir_init(&f);
    float xb[N6_BANDS][N6_HOP12], yb[N6_BANDS][N6_HOP12];
    for (int h = 0; h < NH; ++h) {
        for (int b = 0; b < N6_BANDS; ++b)
            memcpy(xb[b], x + (size_t)b * NT + (size_t)h * N6_HOP12,
                   N6_HOP12 * sizeof(float));
        n6_fir_hop(&f, &c, tv[h], (const float (*)[N6_HOP12])xb, yb, N6_HOP12);
        for (int b = 0; b < N6_BANDS; ++b)
            memcpy(&y[b][h * N6_HOP12], yb[b], N6_HOP12 * sizeof(float));
    }
    double e = rel_rms(&y[0][0], yg, (size_t)N6_BANDS * NT);
    /* check at the same time that a state reset really does erase the history */
    n6_fir_reset(&f);
    int zeroed = 1;
    for (int b = 0; b < N6_BANDS; ++b)
        for (int k = 0; k < N6_FIR_HIST; ++k)
            if (f.hist[b][k] != 0.0f) zeroed = 0;
    int ok = (e < 1e-5) && zeroed;
    printf("[fir]         rel RMS = %.3e  reset=%d  %s\n", e, zeroed,
           ok ? "OK" : "FAIL");
    free(w0); free(w1); free(x); free(tv); free(yg);
    return ok;
}

/* 5) FIR IN THE CHAIN (D-17): the linear layer enters the mix exactly once
 *    per voice, on the correct ping-pong block and with the correct t axis.
 *    The method is the "null teacher": residual = -input cancels the skeleton
 *    exactly, and everything left at the output is the FIR's contribution.
 *    Hiss and wow depth are off, the chord velocity is lowered (vel 30) so
 *    that the limiter stays transparent.
 *    (a) w0 = unit impulse (FIR(x) = x): a NEGX chain with such a FIR must
 *        match the plain skeleton (ZERO stub, FIR off) — the per-sample sum
 *        goes as (sk - sk) + sk and gives exactly sk;
 *    (b) w0 = 0, w1 = impulse, t_macro = 0.5 (FIR(x) = 0.5x): the same chain
 *        must give half the plain skeleton — the path of the t axis and of
 *        the w1 term;
 *    (c) after CC123 and flushing the tail, the FIR history is STRICT zeros:
 *        skipping silent voices is exact, not approximate. */
static int test_fir_chain(void)
{
    static float w_id[N6_BANDS * N6_BANDS * N6_FIR_TAPS];
    static float w_zero[N6_BANDS * N6_BANDS * N6_FIR_TAPS];
    for (int b = 0; b < N6_BANDS; ++b)
        w_id[((size_t)b * N6_BANDS + b) * N6_FIR_TAPS] = 1.0f;
    const n6_fir_coeffs_t c_id = { w_id, w_zero };    /* FIR(x) = x   */
    const n6_fir_coeffs_t c_t  = { w_zero, w_id };    /* FIR(x) = t*x */

    n6_params_t prm = N6_PARAMS_DEFAULT;
    prm.n_voices = 3;
    enum { NH = 200 };
    static float o_ref[NH * N6_HOP48], o_id[NH * N6_HOP48],
                 o_t[NH * N6_HOP48],  o_half[NH * N6_HOP48];

    /* reference: plain skeleton — ZERO stub, FIR off (the chain before D-17) */
    n6_pipe_t *q = malloc(sizeof *q);
    n6_pipe_init(q, &prm);
    q->hisslvl = 0.0f; q->wdepth = 0.0f;
    n6_pipe_set_fir(q, NULL);
    play_chord_vel(q, 30);
    for (int h = 0; h < NH; ++h) n6_pipe_hop(q, o_ref + (size_t)h * N6_HOP48);

    /* (a) NEGX + identity FIR */
    n6_pipe_t *p = malloc(sizeof *p);
    n6_pipe_init(p, &prm);
    p->hisslvl = 0.0f; p->wdepth = 0.0f;
    n6_npu_test_pattern(p->npu, N6_NPUT_NEGX);
    n6_npu_test_latency(p->npu, 2);
    n6_pipe_set_fir(p, &c_id);
    play_chord_vel(p, 30);
    for (int h = 0; h < NH; ++h) n6_pipe_hop(p, o_id + (size_t)h * N6_HOP48);

    /* (b) NEGX + FIR = t*x with t_macro = 0.5 */
    n6_pipe_t *r = malloc(sizeof *r);
    n6_pipe_init(r, &prm);
    r->hisslvl = 0.0f; r->wdepth = 0.0f; r->t_macro = 0.5f;
    n6_npu_test_pattern(r->npu, N6_NPUT_NEGX);
    n6_npu_test_latency(r->npu, 2);
    n6_pipe_set_fir(r, &c_t);
    play_chord_vel(r, 30);
    for (int h = 0; h < NH; ++h) n6_pipe_hop(r, o_t + (size_t)h * N6_HOP48);

    double peak_ref = 0.0;
    for (size_t i = 0; i < (size_t)NH * N6_HOP48; ++i) {
        if (fabs(o_ref[i]) > peak_ref) peak_ref = fabs(o_ref[i]);
        o_half[i] = 0.5f * o_ref[i];
    }
    double ea = rel_rms(o_id, o_ref,  (size_t)NH * N6_HOP48);
    double eb = rel_rms(o_t,  o_half, (size_t)NH * N6_HOP48);

    /* (c) panic + release tail: the FIR history must become an exact zero.
     * The release is exponential with zeroing at the 1e-4 threshold (voice.c)
     * — env takes ~1.5 s to reach an exact zero, hence 450 hops. */
    n6_midi_ev_t panic = { N6_EV_CC, 0, 123, 0 };
    n6_vm_event(&p->vm, &panic);
    static float tail[N6_HOP48];
    for (int h = 0; h < 450; ++h) n6_pipe_hop(p, tail);
    int hist_zero = 1;
    for (int v = 0; v < prm.n_voices; ++v)
        for (int b = 0; b < N6_BANDS; ++b)
            for (int k = 0; k < N6_FIR_HIST; ++k)
                if (p->fir[v].hist[b][k] != 0.0f) hist_zero = 0;

    /* peak_ref in (0.005, 0.9): the chord is audible, the limiter is
     * transparent — otherwise comparisons (a)/(b) lose meaning, change vel */
    int ok = ea < 1e-6 && eb < 1e-5 && peak_ref > 0.005 && peak_ref < 0.9
          && hist_zero && p->npu_miss == 0 && r->npu_miss == 0;
    printf("[fir chain]   id=%.3e t*x=%.3e peak_ref=%.3f hist0=%d  %s\n",
           ea, eb, peak_ref, hist_zero, ok ? "OK" : "FAIL");
    free(p); free(q); free(r);
    return ok;
}

/* 7) Auto-unison and drift (D-19): a single note is duplicated by a free
 *    voice with detune; a chord steals the slave first; NoteOff drops the
 *    pair; drift moves f0 within the declared bounds. The defaults (zeros)
 *    need no separate test: every golden above checks them. */
static int test_unison(void)
{
    n6_params_t prm = N6_PARAMS_DEFAULT;
    prm.uni_cents = 7.0f; prm.drift_cents = 3.0f;
    n6_voicemgr_t m; n6_vm_init(&m, &prm);
    n6_frame_t fr[N6_MAX_VOICES];
    n6_midi_ev_t on60 = { N6_EV_NOTE_ON, 0, 60, 100 };
    n6_midi_ev_t on64 = { N6_EV_NOTE_ON, 0, 64, 100 };
    n6_midi_ev_t off60 = { N6_EV_NOTE_OFF, 0, 60, 0 };
    n6_midi_ev_t off64 = { N6_EV_NOTE_OFF, 0, 64, 0 };

    n6_vm_event(&m, &on60);
    int on = 0, slaves = 0; double lf[2]; int nlf = 0;
    for (int i = 0; i < prm.n_voices; ++i) {
        if (m.v[i].st == V_ON) { on++; if (nlf < 2) lf[nlf++] = m.v[i].logf0_tgt; }
        if (m.v[i].uni_slave) slaves++;
    }
    double cents = nlf == 2 ? fabs(lf[1] - lf[0]) / (M_LN2 / 1200.0) : 0.0;
    int pair_ok = (on == 2 && slaves == 1 && fabs(cents - 7.0) < 0.01);

    n6_vm_event(&m, &on64);                     /* chord: the slave is stolen */
    int n60 = 0, n64 = 0, sl_on = 0;
    for (int i = 0; i < prm.n_voices; ++i)
        if (m.v[i].st == V_ON) {
            if (m.v[i].note == 60) n60++;
            if (m.v[i].note == 64) n64++;
            sl_on += m.v[i].uni_slave;
        }
    int steal_ok = (n60 == 1 && n64 == 1 && sl_on == 0);

    n6_vm_event(&m, &off60); n6_vm_event(&m, &off64);
    int off_ok = 1;
    for (int i = 0; i < prm.n_voices; ++i)
        if (m.v[i].st == V_ON) off_ok = 0;

    /* drift: over 200 ticks f0 moves, but within ±4σ = 12 cents */
    n6_vm_event(&m, &on60);
    double f0ref = 440.0 * pow(2.0, (60 - 69) / 12.0);
    double devmax = 0.0, devmin = 1e9;
    for (int k = 0; k < 200; ++k) {
        n6_vm_tick(&m, fr);
        for (int i = 0; i < prm.n_voices; ++i)
            if (m.v[i].st == V_ON && !m.v[i].uni_slave) {
                double c = 1200.0 * log2((double)fr[i].f0 / f0ref);
                if (c > devmax) devmax = c;
                if (c < devmin) devmin = c;
            }
    }
    int drift_ok = (devmax - devmin) > 0.05 && devmax < 12.0 && devmin > -12.0;

    int ok = pair_ok && steal_ok && off_ok && drift_ok;
    printf("[unison]      pair=%d (%.2f c) steal=%d off=%d drift=%d (%.2f..%.2f c)  %s\n",
           pair_ok, cents, steal_ok, off_ok, drift_ok, devmin, devmax,
           ok ? "OK" : "FAIL");
    return ok;
}

int main(void)
{
    int ok = 1;
    ok &= test_pqmf();
    ok &= test_skeleton_b();
    ok &= test_wowflutter();
    ok &= test_midi();
    ok &= test_voice_pipe();
    ok &= test_npu_layout();
    ok &= test_npu_null_teacher();
    ok &= test_sustain();
    ok &= test_fir();
    ok &= test_fir_chain();
    ok &= test_unison();
    printf(ok ? "== ALL TESTS OK ==\n" : "== THERE ARE FAILURES ==\n");
    return ok ? 0 : 1;
}
