#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
export_fw_assets.py — assets for the firmware and its host tests:
  fw/n6_bandresp.h       — the complex table g_k(f) of skeleton B (B-2)
  fw/test/vectors/*.bin  — golden vectors §2.4 as flat float32 LE
.bin format: raw float32; the dimensions are hardcoded in host_test.c and
checked against the file size. Run: python3 export_fw_assets.py
"""
import os
import sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, os.path.join(ROOT, "dsp"))
import skeleton_b as skb                                    # noqa: E402

FW = os.path.join(ROOT, "fw")
VEC = os.path.join(FW, "test", "vectors")


def write_bandresp_header():
    re, im = skb._GRE, skb._GIM                             # (4, 961)
    n = re.shape[1]
    with open(os.path.join(FW, "n6_bandresp.h"), "w") as f:
        f.write("/* Autogenerated by tools/export_fw_assets.py — do not edit.\n"
                f" * Complex response of the bank g_k(f) (skeleton_b B-2, v5),\n"
                f" * grid {skb.GRID_HZ:.0f} Hz, 0..24000, {n} points x 4 bands.\n"
                " * Phase convention: cumsum@48k (B-1). */\n"
                f"#define N6_BANDRESP_N {n}\n"
                f"#define N6_BANDRESP_GRID_HZ {skb.GRID_HZ}f\n\n")
        for name, arr in (("n6_bandresp_re", re), ("n6_bandresp_im", im)):
            f.write(f"static const float {name}[4][{n}] = {{\n")
            for b in range(4):
                row = ", ".join(f"{v:+.8e}f" for v in arr[b])
                f.write("  { " + row + " },\n")
            f.write("};\n\n")
    print(f"n6_bandresp.h: 4 x {n}")


def dump(name, a):
    a = np.asarray(a, dtype=np.float32)
    a.tofile(os.path.join(VEC, name + ".bin"))
    print(f"{name}.bin: {a.size} f32")


if __name__ == "__main__":
    os.makedirs(VEC, exist_ok=True)
    write_bandresp_header()
    g = np.load(os.path.join(ROOT, "dsp", "golden", "pqmf_synth_io.npz"))
    dump("pqmf_sub", g["sub"])              # (4, 28800)
    dump("pqmf_y", g["y"])                  # (115200,)
    g = np.load(os.path.join(ROOT, "dsp", "golden", "skeleton_b_io.npz"))
    for k in ("f0", "amp", "tA", "tB", "gate"):
        dump("skb_" + k, g[k])              # (600,)
    dump("skb_sub", g["sub"])               # (4, 28800)
    g = np.load(os.path.join(ROOT, "dsp", "golden", "wowflutter_io.npz"))
    dump("wf_x", g["x"])                    # (115200,)
    for k in ("v_macro", "depth", "hiss"):
        dump("wf_" + k, g[k])               # (600,)
    dump("wf_y", g["y"])                    # (115200,)
    print("done:", VEC)
