#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
export_fir.py — coefficients of the linear zeroth layer from a checkpoint into the firmware.

Context: exam_delta showed that the runtime is a FIR on the M55 plus the network
on the NPU on top of it (delta +9.18 dB on a 28-minute corpus). The FIR is fitted
by least squares (probe_linear.fit_fir) and stored in ckpt_delta*.pt in the
"fir_W" field. Here it is repacked into the layout fw/src/n6_fir.c expects:

    W from LS: W[(bp*K + k), b]        (b — output band, bp — input band)
    in C:      w0[b][bp][k], w1[b][bp][k]
    y[b][n] = SUM_{bp,k} (w0 + t*w1)[b][bp][k] * x[bp][n-k]

The first half of W's rows is W0, the second (offset 4*K) is W1 (modulation by the t axis).

Run:
  python export_fir.py --ckpt ../teacher_search/A2_ottpress/ckpt_delta_p360.pt
  python export_fir.py --selftest        # without torch: layout check on numpy
"""
import argparse
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
BANDS = 4


def split_w(W, taps):
    """W[8*taps, 4] -> (w0, w1) in the C layout [b][bp][k]."""
    W = np.asarray(W, np.float64)
    assert W.shape == (8 * taps, BANDS), W.shape
    out = []
    for half in (0, 4 * taps):
        c = np.empty((BANDS, BANDS, taps), np.float64)
        for b in range(BANDS):
            for bp in range(BANDS):
                c[b, bp, :] = W[half + bp * taps: half + (bp + 1) * taps, b]
        out.append(c)
    return out[0], out[1]


def eval_c_layout(w0, w1, x, t, taps):
    """Exactly what n6_fir_hop does — for cross-checking the layout."""
    B, n = x.shape[0], x.shape[1]
    xp = np.concatenate([np.zeros((B, taps - 1)), x], axis=1)
    y = np.zeros((B, n))
    for i in range(n):
        w = w0 + t[i] * w1
        seg = xp[:, i:i + taps][:, ::-1]              # [bp][k], k=0 -> sample n
        for b in range(BANDS):
            y[b, i] = float((w[b] * seg).sum())
    return y


def _cfloat(v):
    """A valid C float literal. "%.9g" on a round number gives "1", and gluing
    "f" onto it produces "1f" — which is NOT a floating-point constant: the C
    standard requires either a dot or an exponent. The build died on the very
    first include. Found on 3 Aug while preparing M2, before the first firmware build."""
    v = float(v)
    if v != v or v in (float("inf"), float("-inf")):
        raise ValueError("non-numeric coefficient for the header: %r" % v)
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit_header(w0, w1, taps, path, meta):
    def arr(name, a):
        s = ["static const float %s[%d * %d * %d] = {" % (name, BANDS, BANDS, taps)]
        flat = a.reshape(-1).astype(np.float32)
        for i in range(0, flat.size, 6):
            s.append("    " + ", ".join(_cfloat(v) for v in flat[i:i + 6]) + ",")
        s.append("};")
        return "\n".join(s)

    txt = f"""/* n6_fir_coeffs.h — GENERATED BY tools/export_fir.py, DO NOT EDIT BY HAND.
 * Source: {meta['ckpt']}
 * Taps K = {taps}; layout [b][bp][k] (see fw/src/n6_fir.h).
 * Residual suppression by this filter alone on hold-out: {meta['fir_db']}
 */
#ifndef N6_FIR_COEFFS_H
#define N6_FIR_COEFFS_H
#include "src/n6_fir.h"

#if N6_FIR_TAPS != {taps}
#error "n6_fir_coeffs.h was built for a different N6_FIR_TAPS - regenerate it"
#endif

{arr('n6_fir_w0', w0)}

{arr('n6_fir_w1', w1)}

static const n6_fir_coeffs_t n6_fir_coeffs = {{ n6_fir_w0, n6_fir_w1 }};
#endif
"""
    open(path, "w", encoding="utf-8", newline="\n").write(txt)
    return len(txt)


def selftest():
    rng = np.random.default_rng(20260802)
    taps = 17
    W = rng.standard_normal((8 * taps, BANDS)) * 0.05
    x = rng.standard_normal((BANDS, 400)) * 0.1
    t = np.clip(0.5 + 0.4 * np.sin(np.linspace(0, 5, 400)), 0, 1)

    w0, w1 = split_w(W, taps)
    y_c = eval_c_layout(w0, w1, x, t, taps)

    # reference — exactly the probe_linear.fir_features/fir_predict formula
    n = x.shape[1]
    cols = []
    for b in range(BANDS):
        for k in range(taps):
            v = np.concatenate([np.zeros(k), x[b, :n - k]]) if k else x[b]
            cols.append(v)
    P = np.stack(cols, 1)
    Phi = np.concatenate([P, P * t[:, None]], axis=1)
    y_ref = (Phi @ W).T

    e = np.sqrt(((y_c - y_ref) ** 2).mean() / ((y_ref ** 2).mean() + 1e-30))
    print("layout [b][bp][k] against probe_linear: rel RMS = %.3e" % e)
    assert e < 1e-12, e

    p = os.path.join(HERE, "_selftest_fir_coeffs.h")
    nbytes = emit_header(w0, w1, taps, p, dict(ckpt="selftest", fir_db="n/a"))
    txt = open(p, encoding="utf-8").read()
    nfloat = txt.count("f,")
    print("header: %d bytes, %d numbers (expected %d)" % (nbytes, nfloat, 2 * BANDS * BANDS * taps))
    assert nfloat == 2 * BANDS * BANDS * taps
    os.remove(p)
    print("SELFTEST OK")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", default=os.path.join(
        HERE, "..", "teacher_search", "A2_ottpress", "ckpt_delta.pt"))
    ap.add_argument("--out", default=os.path.join(HERE, "..", "fw",
                                                  "n6_fir_coeffs.h"))
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return selftest()

    import torch
    ck = torch.load(args.ckpt, map_location="cpu")
    if "fir_W" not in ck:
        sys.exit("the checkpoint has no fir_W — this is not a ckpt_delta*.pt")
    taps = int(ck.get("taps", 65))
    w0, w1 = split_w(np.asarray(ck["fir_W"]), taps)
    if taps != 65:
        print("WARNING: taps=%d, but fw/src/n6_fir.h has N6_FIR_TAPS=65 — "
              "fix the define or re-run the FIR with --taps 65" % taps)
    n = emit_header(w0, w1, taps, args.out,
                    dict(ckpt=os.path.basename(args.ckpt),
                         fir_db="see teacher_search/exam_delta*.md"))
    print("%s: %d bytes, K=%d, |w0|max=%.4g |w1|max=%.4g"
          % (args.out, n, taps, np.abs(w0).max(), np.abs(w1).max()))


if __name__ == "__main__":
    main()
